In [1]:
# Import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

DATA_DIR = Path("../data/raw")
# plt.style.use('default')

In [2]:
# A month loading
df_jan = pd.read_parquet(DATA_DIR / "yellow_tripdata_2023-01.parquet")
print(f"Shape: {df_jan.shape}")
df_jan.head()

Shape: (3066766, 19)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.3,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.9,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.9,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.1,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.4,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00

In [78]:
neg_total_amount = len(df_jan[df_jan["total_amount"] < 0])
df_jan.shape[0]
print(f'{neg_total_amount} negative rows in the total_amount column')
print(f'total_amount: {neg_total_amount / df_jan.shape[0] * 100:.2f}%')

25204 negative rows in the total_amount column
total_amount: 0.82%

In [77]:
neg_trip_distance = len(df_jan[df_jan['trip_distance'] < 0])
df_jan.shape[0]
print(f'{neg_trip_distance} negative rows are in the trip_distance column')
print(f'total_amount: {neg_trip_distance / df_jan.shape[0] * 100:.2f}%')

0 negative rows are in the trip_distance column
total_amount: 0.00%

In [76]:
(df_jan['tpep_pickup_datetime'] > df_jan['tpep_dropoff_datetime']).value_counts()
print("In 3 rows there are negative duration time")
df_jan[df_jan['tpep_pickup_datetime'] > df_jan['tpep_dropoff_datetime']]

In 3 rows there are negative duration time

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
1839180,1,2023-01-20 13:35:00,2023-01-20 13:05:48,1.0,0.8,99.0,N,227,14,1,16.5,0.0,0.5,0.0,0.0,1.0,18.0,0.0,0.0
2124414,1,2023-01-23 10:43:58,2023-01-23 10:29:26,1.0,2.4,99.0,N,102,82,1,21.5,0.0,0.5,0.0,0.0,1.0,23.0,0.0,0.0
2218504,1,2023-01-24 11:00:00,2023-01-24 10:40:48,1.0,0.4,99.0,N,247,169,1,15.5,0.0,0.5,0.0,0.0,1.0,17.0,0.0,0.0

In [80]:
print(f"Zero passenger: {(df_jan['passenger_count'] == 0).sum()}")
print(f"NaN passenger:  {df_jan['passenger_count'].isnull().sum()}")
print(f"Total problems: {((df_jan['passenger_count'] == 0) | df_jan['passenger_count'].isnull()).sum()}")

Zero passenger: 51164
NaN passenger:  71743
Total problems: 122907

In [79]:
null_counts = df_jan.isnull().sum()
null_columns = null_counts[null_counts > 0]
print(f"Null values in {len(null_columns)} columns:")
print(null_columns)

Null values in 5 columns:
passenger_count         71743
RatecodeID              71743
store_and_fwd_flag      71743
congestion_surcharge    71743
airport_fee             71743
dtype: int64